### ISSUE TITLE
No support for Telegram Desktop 1.6?

### ISSUE THREAD

**Issue by reallyuniquename** [mxs42/mutegram#4]
It seems it doesn't work for the latest Telegram version.

**Comment by mxs42** [comment]
Working on it...
Actually may introduce more stable solution soon based on different mechanism.

**Comment by mxs42** [comment]
Fixed in d4f88ea.
Actually can be done using different mechanism like I said, I thought about using proxy DLL to hook FlashWindowEx in runtime, essentially making it 100% future-proof.
Let's see for how long this signature can survive though.

**Comment by mxs42** [comment]
I pushed proxy-dll branch and released binaries, it should _probably_ work with any Telegram Desktop version on any Windows version, it doesn't requires patching executable because it does things in runtime. It doesn't need signatures to work so it's should be 100% future-proof because it doesn't rely on Telegram source code at all (although it relies on winmm.dll Telegram dependency).  
Feel free to test it and let me know if something isn't working / broken since I never used this technique before.
