### ISSUE TITLE
Signature for Telegram Desktop 1.9.x

### ISSUE THREAD

**Issue by reallyuniquename** [mxs42/mutegram#5]
If someone prefers to use binary patch instead of proxy DLL here is new signature `FF 15 ? ? ? ? 3B 86 ? ? ? ? 74 ?` and target offset `0x0c`.

**Comment by mxs42** [comment]
Why patch though? I haven't encountered any issues with DLL proxy.
Also it's a shame they STILL ignore feature request to add such basic function. Like, it's a matter of one checkbox and several conditions in code.

**Comment by reallyuniquename** [comment]
I guess proxying entire DLL seems like an overkill to me when you can just patch 1 byte instead. New signature should be compatible with newer versions for some time (worked alright with ~~1.9.4~~ ~~1.9.7~~ 2.0.1).

**Comment by mxs42** [comment]
Fair enough.

**Comment by mmangelsdorf** [comment]
I like this idea, too! Could you point me to some documentation on how to apply the patch? Would I open `Telegram.exe` in a hex editor and replace 0x0c with the bytes you posted?

**Comment by reallyuniquename** [comment]
@Merlin2001 
If you want to just patch Telegram binary then you would need to download https://github.com/mxs42/mutegram/tree/master, replace corresponding constants with bytes from the first post and compile it.

Or you can use proxy DLL instead, it's much easier way, see https://github.com/mxs42/mutegram/releases/latest.

**Comment by mmangelsdorf** [comment]
Oh yeah, I'm currently using the proxy DLL method and it works perfectly fine. I was just curious how the patching process would work.

**Comment by reallyuniquename** [comment]
I guess you can do that with hex editor too if it allows you to find patterns. You would need to locate said sequence and replace 12th byte with `0xEB`.

**Comment by mxs42** [comment]
It's ridiculous that they do big updates and stuff and yet they don't add one checkbox to disable that call to `FlashWindowEx`...
I thought about pull-requesting it on my own but honestly I don't care since we have this repo.

**Comment by mxs42** [comment]
Not needed anymore, they added a checkbox to disable taskbar flash. 
Wow!

**Comment by reallyuniquename** [comment]
Hey @mxs42!

If you still use Telegram Desktop you may have noticed they now serve ads. I'm wondering if you've given a thought towards patching it out in the same neat manner.

**Comment by reallyuniquename** [comment]
Also pinging @Kadeluxe.

**Comment by Kadeluxe** [comment]
> Hey @mxs42!
> 
> If you still use Telegram Desktop you may have noticed they now serve ads. I'm wondering if you've given a thought towards patching it out in the same neat manner.

Hi there!
Yes, I still use Telegram Desktop daily. In fact Telegram is the only «social» app that I use at all.

So yeah, I'm aware of their updates regarding ads. Personally I only saw ads for a couple of days, then it stopped showing in all channels where I could see. No idea why, maybe it's a part of their staged rollout. 

Still, from what I saw it was very subtle and wasn't bothering me at all. I will see how it goes in the future, when they start serving ads to all users.

Regarding patching: quick looking at the Telegram Desktop source suggests that they implemented it in a clean way, at least they didn't go with some kind of obfuscation or something. 

I'm not sure about byte-patching though (how it was done initially in this repo), honestly it looks that it may be easier to fork Telegram Desktop and do a code-patch. 

The reason why I think code-patching is more viable is that (again, judging by a quick look) there is no «single entry point» as it was with taskbar flashing. Telegram also tracks if you «view» sponsored messages, they have special API method `channels.viewSponsoredMessage` for that so «proper» removing of ads should still call their servers but never display ads in UI so they can not track that you use some client that violates their ToS ([they require all 3rd party apps to show sponsored messages](https://corefork.telegram.org/api/sponsored-messages#sponsored-messages-in-third-party-apps)).

Also Github has proper CI/CD now. I initially went with byte-patch approach because it was a quick way to avoid setting up the whole build environment and compiling client after each update. Now it can be done automatically using Github Actions on Github servers so it's clearly way less hassle.

Overall, I don't have specific plans about it for now but I may consider forking Telegram Desktop and patching it in the future.

Meanwhile I would keep an eye on existing Telegram Desktop fork — [kotatogram](https://github.com/kotatogram/kotatogram-desktop). I use it for all my other accounts apart from personal one, I think it's the most feature-rich Telegram Desktop fork available, and it may be interesting to see how they are going to handle ads (they haven't updated it yet).

**Comment by reallyuniquename** [comment]
Thanks for looking into this. I haven't considered one can build Telegram with Github Actions without setting up local environment!

> Telegram also tracks if you «view» sponsored messages

Yikes I wasn't aware of that and was thinking about patching conditional jumps after `from->loadedAtBottom()` is called or something like that. I guess that kind of ad blocking would be easily detectable by the server and might lead to account ban. Although that's exactly what is done on Android.
https://github.com/shatyuka/Killergram/blob/38601a79ec40335b293d984ccaf03c03df7f0ab5/app/src/main/java/com/shatyuka/killergram/MainHook.java#L31-L32

Now I'm wondering what would be the cleanest way to hide ad widget without altering any tracking functions.

**Comment by Kadeluxe** [comment]
> I haven't considered one can build Telegram with Github Actions without setting up local environment!

Kotatogram does this, they build Telegram for Windows, Linux and MacOS using Github Actions. One can probably just copy their run files with slight modifications.

Regarding views tracking: I don't think they are actually going to check all API requests and do something so maybe it's not worth it to do it «properly» and just removing some jumps is fine.

If we talk about something more complex, then there is [HistoryInner::paintEvent](https://github.com/telegramdesktop/tdesktop/blob/6850cc5ab405154d6410ee1dde1db57a448393bb/Telegram/SourceFiles/history/history_inner_widget.cpp#L799) which apparently renders chat history and indeed tracks sponsored messages views. I think it's possible to just skip rendering sponsored messages here without removing that `session().data().sponsoredMessages().view(item->fullId());` call. But this is surely too much for byte-patching.
